# Generated by Django 4.1.6 on 2023-02-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.department')),
            ],
        ),
    ]
