# Generated by Django 4.1.6 on 2023-02-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_department_id_alter_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department_id',
            new_name='department',
        ),
    ]
