# Generated by Django 4.1.6 on 2023-02-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_rename_department_id_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='id',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='employee_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id', to='demoapp.department'),
        ),
    ]
